branch-defaults:
  default:
    environment: weathrio-dev
environment-defaults:
  weathrio-dev:
    branch: null
    repository: null
global:
  application_name: weathr.io
  default_ec2_keyname: null
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
